<?php

namespace App\Domain\Maintenance\Services;

use App\Domain\Maintenance\Enums\WorkOrderStatus;
use App\Domain\Maintenance\Enums\WorkOrderType;
use App\Models\WorkOrder;

/**
 * Derives the "Mission Workspace" presentation data for a Work Order from
 * fields and relations that already exist on the model — no new columns,
 * no new tables. Kept out of the Eloquent model and out of Vue so the
 * derivation rules (expected-outcome templates, the canonical progress
 * spine) live in one testable place.
 */
class WorkOrderMissionPresenter
{
    /** The "happy path" a work order travels — On Hold/Cancelled are excursions from it, not stops on it. */
    private const PROGRESS_SPINE = [
        WorkOrderStatus::Draft,
        WorkOrderStatus::Planned,
        WorkOrderStatus::InProgress,
        WorkOrderStatus::Completed,
        WorkOrderStatus::Verified,
        WorkOrderStatus::Closed,
    ];

    /**
     * A deterministic, template-based phrase — never generated by parsing
     * free text (failure_cause/description), which would be more specific
     * but silently fragile. One of five fixed phrases per WorkOrderType,
     * with the corrective case split by whether the equipment is stopped.
     */
    public function expectedOutcome(WorkOrder $workOrder): string
    {
        if ($workOrder->work_order_type === WorkOrderType::Corrective) {
            return $workOrder->equipment_stopped
                ? 'Restablecer la operación del equipo'
                : 'Eliminar la falla antes de que detenga el equipo';
        }

        return match ($workOrder->work_order_type) {
            WorkOrderType::Preventive => 'Mantener la disponibilidad y prevenir fallas',
            WorkOrderType::Predictive => 'Confirmar el estado real del equipo antes de que falle',
            WorkOrderType::Improvement => 'Aumentar la confiabilidad o el desempeño del equipo',
            WorkOrderType::Emergency => 'Recuperar la operación segura en el menor tiempo posible',
            default => 'Completar el trabajo definido en esta orden',
        };
    }

    /**
     * @return array{stages: list<array{status:string,label:string,done:bool,current:bool,at:?string}>, percentage:int, current_status:string, off_spine:?array{status:string,label:string}}
     */
    public function progress(WorkOrder $workOrder): array
    {
        $status = $workOrder->status;
        // On Hold reads as "paused inside In Progress" on the spine; Cancelled
        // freezes the spine wherever it stood without claiming a false stage.
        $spineStatus = match ($status) {
            WorkOrderStatus::OnHold => WorkOrderStatus::InProgress,
            WorkOrderStatus::Cancelled => $this->lastReachedSpineStatus($workOrder),
            default => $status,
        };

        $currentIndex = array_search($spineStatus, self::PROGRESS_SPINE, strict: true);
        $currentIndex = $currentIndex === false ? 0 : $currentIndex;
        $isClosed = $status === WorkOrderStatus::Closed;

        $stages = [];
        foreach (self::PROGRESS_SPINE as $index => $stageStatus) {
            // A stage is filled once the WO has moved past it — the final
            // (Closed) node is also filled once reached, not just "current".
            $stages[] = [
                'status' => $stageStatus->value,
                'label' => $stageStatus->label(),
                'done' => $index < $currentIndex || ($index === $currentIndex && $isClosed),
                'current' => $index === $currentIndex && $status !== WorkOrderStatus::Cancelled,
                'at' => $this->timestampFor($workOrder, $stageStatus),
            ];
        }

        $lastIndex = count(self::PROGRESS_SPINE) - 1;
        $percentage = $lastIndex > 0 ? (int) round(($currentIndex / $lastIndex) * 100) : 0;

        return [
            'stages' => $stages,
            'percentage' => $percentage,
            'current_status' => $status->value,
            'off_spine' => in_array($status, [WorkOrderStatus::OnHold, WorkOrderStatus::Cancelled], strict: true)
                ? ['status' => $status->value, 'label' => $status->label()]
                : null,
        ];
    }

    /**
     * The most recent OTHER work order on the same equipment — minimal
     * context ("what happened before"), not a full history.
     *
     * @return array{id:string,work_order_number:string,title:string,type:string,closed_at:?string,created_at:string}|null
     */
    public function previousIntervention(WorkOrder $workOrder): ?array
    {
        if (! $workOrder->equipment_id) {
            return null;
        }

        $previous = WorkOrder::query()
            ->where('equipment_id', $workOrder->equipment_id)
            ->where('id', '!=', $workOrder->id)
            ->orderByDesc('created_at')
            ->first();

        if (! $previous) {
            return null;
        }

        return [
            'id' => $previous->id,
            'work_order_number' => $previous->work_order_number,
            'title' => $previous->title,
            'type' => $previous->work_order_type?->label(),
            'closed_at' => $previous->closed_at?->toISOString() ?? $previous->completed_at?->toISOString(),
            'created_at' => $previous->created_at->toISOString(),
        ];
    }

    /**
     * Where this work order came from — a request someone reported, or a
     * preventive plan that generated it. Null when created directly.
     *
     * @return array{type:'request'|'plan',label:string,description:?string}|null
     */
    public function origin(WorkOrder $workOrder): ?array
    {
        if ($workOrder->relationLoaded('maintenanceRequest') && $workOrder->maintenanceRequest) {
            return [
                'type' => 'request',
                'label' => 'Solicitud reportada',
                'description' => $workOrder->maintenanceRequest->title ?? $workOrder->maintenanceRequest->description,
            ];
        }

        if ($workOrder->relationLoaded('maintenancePlan') && $workOrder->maintenancePlan) {
            return [
                'type' => 'plan',
                'label' => 'Plan de mantenimiento preventivo',
                'description' => $workOrder->maintenancePlan->name,
            ];
        }

        return null;
    }

    /**
     * The plan's task list, shown as read-only guidance in the Evidence Zone
     * checklist — reuses MaintenancePlanTask (an existing model under
     * Maintenance Plans), never a WorkOrder-owned table. There is no
     * per-work-order "checked" state to persist, so this is guidance to
     * verify against, not a record of what was done — the real evidence of
     * completion is the photos/notes/time already captured.
     *
     * @return list<array{id:string,title:string,description:?string}>
     */
    public function checklist(WorkOrder $workOrder): array
    {
        if (! $workOrder->relationLoaded('maintenancePlan') || ! $workOrder->maintenancePlan) {
            return [];
        }

        if (! $workOrder->maintenancePlan->relationLoaded('tasks')) {
            return [];
        }

        return $workOrder->maintenancePlan->tasks
            ->map(fn ($task) => [
                'id' => $task->id,
                'title' => $task->title,
                'description' => $task->description,
            ])
            ->values()
            ->all();
    }

    /**
     * What's required before this work order can honestly be marked
     * Completed. Every item is derived from relations/fields that already
     * exist — nothing new is persisted here, this only reads. `blocking`
     * items keep the frontend's confirm button disabled; non-blocking ones
     * are shown as a heads-up but don't stop the technician.
     *
     * @return list<array{key:string,label:string,satisfied:bool,blocking:bool,hint:string}>
     */
    public function completionReadiness(WorkOrder $workOrder): array
    {
        $hasEvidence = $workOrder->relationLoaded('attachments') && $workOrder->attachments->isNotEmpty();
        $hasSignature = $workOrder->relationLoaded('signatures')
            ? $workOrder->signatures->contains(fn ($s) => $s->signature_type?->value === 'technician_completion')
            : false;
        $hasResult = filled($workOrder->work_performed);
        $checklistTotal = count($this->checklist($workOrder));

        return [
            [
                'key' => 'result',
                'label' => 'Resultado obtenido descrito',
                'satisfied' => $hasResult,
                'blocking' => true,
                'hint' => $hasResult ? '' : 'Describe qué se hizo y cómo quedó el equipo antes de cerrar la misión.',
            ],
            [
                'key' => 'signature',
                'label' => 'Firma del técnico',
                'satisfied' => $hasSignature,
                'blocking' => true,
                'hint' => $hasSignature ? '' : 'Falta la firma del técnico que ejecutó el trabajo.',
            ],
            [
                'key' => 'evidence',
                'label' => 'Evidencia fotográfica',
                'satisfied' => $hasEvidence,
                'blocking' => false,
                'hint' => $hasEvidence ? '' : 'No se registraron fotos — recomendado, no obligatorio.',
            ],
            [
                'key' => 'checklist',
                'label' => 'Tareas del plan verificadas',
                'satisfied' => $checklistTotal === 0,
                'blocking' => false,
                'hint' => $checklistTotal === 0 ? '' : "Repasa las {$checklistTotal} tareas del plan antes de confirmar.",
            ],
        ];
    }

    /**
     * The "before you confirm" recap — equipment, time spent, evidence
     * count, checklist status, expected vs. actual outcome. All fields are
     * either already-loaded relations or simple aggregates over them.
     *
     * @return array{equipment:?string,time_spent_hours:?float,evidence_count:int,checklist_label:string,expected_outcome:string}
     */
    public function completionSummary(WorkOrder $workOrder): array
    {
        $checklistTotal = count($this->checklist($workOrder));

        return [
            'equipment' => $workOrder->relationLoaded('equipment') ? $workOrder->equipment?->name : null,
            'time_spent_hours' => $workOrder->actual_labor_hours !== null ? (float) $workOrder->actual_labor_hours : null,
            'evidence_count' => $workOrder->relationLoaded('attachments') ? $workOrder->attachments->count() : 0,
            'checklist_label' => $checklistTotal === 0 ? 'Sin tareas de plan asociadas' : "{$checklistTotal} tareas de referencia",
            'expected_outcome' => $this->expectedOutcome($workOrder),
        ];
    }

    private function lastReachedSpineStatus(WorkOrder $workOrder): WorkOrderStatus
    {
        return match (true) {
            $workOrder->verified_at !== null => WorkOrderStatus::Verified,
            $workOrder->completed_at !== null => WorkOrderStatus::Completed,
            $workOrder->started_at !== null => WorkOrderStatus::InProgress,
            $workOrder->planned_start_at !== null => WorkOrderStatus::Planned,
            default => WorkOrderStatus::Draft,
        };
    }

    private function timestampFor(WorkOrder $workOrder, WorkOrderStatus $stage): ?string
    {
        $timestamp = match ($stage) {
            WorkOrderStatus::Draft => $workOrder->created_at,
            WorkOrderStatus::Planned => $workOrder->planned_start_at,
            WorkOrderStatus::InProgress => $workOrder->started_at,
            WorkOrderStatus::Completed => $workOrder->completed_at,
            WorkOrderStatus::Verified => $workOrder->verified_at,
            WorkOrderStatus::Closed => $workOrder->closed_at,
            default => null,
        };

        return $timestamp?->toISOString();
    }
}
