<?php

namespace App\Models;

use App\Domain\Maintenance\Enums\MaintenanceChecklistItemType;
use App\Domain\Shared\Models\BaseModel;
use Database\Factories\WorkOrderChecklistResultFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A single checklist answer captured in the field.
 *
 * `label`, `unit`, `expected_min/max` and `is_required` are a FROZEN copy of the
 * plan's checklist item: editing the plan later must never rewrite what the
 * técnico was actually asked to measure. `is_out_of_range` is a generated column.
 */
#[Fillable([
    'tenant_id',
    'work_order_task_id',
    'maintenance_checklist_item_id',
    'sort_order',
    'label',
    'item_type',
    'unit',
    'expected_min',
    'expected_max',
    'is_required',
    'value_boolean',
    'value_numeric',
    'value_text',
    'photo_path',
    'notes',
    'recorded_at',
    'recorded_by',
])]
class WorkOrderChecklistResult extends BaseModel
{
    /** @use HasFactory<WorkOrderChecklistResultFactory> */
    use HasFactory;

    // `is_out_of_range` is generated by PostgreSQL and deliberately absent from
    // #[Fillable] — it can never be written from PHP.

    // ── Relationships ─────────────────────────────────────────────────────────

    public function task(): BelongsTo
    {
        return $this->belongsTo(WorkOrderTask::class, 'work_order_task_id');
    }

    /** Provenance only. */
    public function checklistItem(): BelongsTo
    {
        return $this->belongsTo(MaintenanceChecklistItem::class, 'maintenance_checklist_item_id');
    }

    public function recordedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'recorded_by');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    public function isAnswered(): bool
    {
        return $this->recorded_at !== null;
    }

    public function hasRange(): bool
    {
        return $this->item_type === MaintenanceChecklistItemType::Numeric
            && ($this->expected_min !== null || $this->expected_max !== null);
    }

    /** Human-readable answer for reports and the OT timeline. */
    public function displayValue(): ?string
    {
        return match ($this->item_type) {
            MaintenanceChecklistItemType::Boolean => match ($this->value_boolean) {
                true => 'Sí',
                false => 'No',
                default => null,
            },
            MaintenanceChecklistItemType::Numeric => $this->value_numeric === null
                ? null
                : rtrim(rtrim(number_format((float) $this->value_numeric, 3, '.', ''), '0'), '.')
                    .($this->unit !== null ? " {$this->unit}" : ''),
            MaintenanceChecklistItemType::Text => $this->value_text,
        };
    }

    /** Signed distance outside the tolerance band — drives alert severity. */
    public function deviation(): ?float
    {
        if (! $this->is_out_of_range || $this->value_numeric === null) {
            return null;
        }

        $value = (float) $this->value_numeric;

        if ($this->expected_min !== null && $value < (float) $this->expected_min) {
            return round($value - (float) $this->expected_min, 3);
        }

        if ($this->expected_max !== null && $value > (float) $this->expected_max) {
            return round($value - (float) $this->expected_max, 3);
        }

        return null;
    }

    /** Range as written on the OT, e.g. "2.0 – 7.1 mm/s". */
    public function expectedRangeLabel(): ?string
    {
        if (! $this->hasRange()) {
            return null;
        }

        $unit = $this->unit !== null ? " {$this->unit}" : '';

        return match (true) {
            $this->expected_min !== null && $this->expected_max !== null => "{$this->expected_min} – {$this->expected_max}{$unit}",
            $this->expected_min !== null => "≥ {$this->expected_min}{$unit}",
            default => "≤ {$this->expected_max}{$unit}",
        };
    }

    // ── Casts ─────────────────────────────────────────────────────────────────

    protected function casts(): array
    {
        return [
            'item_type' => MaintenanceChecklistItemType::class,
            'is_required' => 'boolean',
            'is_out_of_range' => 'boolean',
            'value_boolean' => 'boolean',
            'expected_min' => 'float',
            'expected_max' => 'float',
            'value_numeric' => 'float',
            'recorded_at' => 'datetime',
        ];
    }
}
